
<head>
<link rel="stylesheet" href="http://localhost/Sportymates1/style/entete.css" />
</head>
<body>
<div id="hautaccueil">
    <div id="banniere_image">
          <div id="logo">
              <a href=accueilv2.html><img src="http://localhost/Sportymates1/images/Logo1.png" alt="Logo de Sportymates"/></a>
          </div>
      <div id="inscription">
        <a href="inscrire.html">Inscription </a>
        <a href="pageconnexionadmin.html">Connection</a>
      </div>
      <div id="banniere_description">
        <nav>
            <ul>
                <li><a href="#">A propos |</a></li>
                <li><a href="pagesport.html">Sports |</a></li>
                <li><a href="#">Nos groupes |</a></li>
                <li><a href="rechercheclub.html">Nos clubs |</a></li>
                <li><a href="#">Forum |</a></li>
                <li><a href="#">Aide</a></li>
                <div id="rechercher">
                <input  class="rech" type='text' id='recherche' name='recherche' placeholder=Rechercher... size="20" maxlength="15" >
                <button type=submit> <img src='images/recherchericon.png' alt='image rechercher'/> </button>
             </div>
            </ul>
          </nav>
       </div>
     </div>
   </div>
 </body>
