
<head>
<link rel="stylesheet" href="http://localhost/Sportymates1/style/footer.css" />
</head>

<body>
  <div id=footer>
    <div class="Autres pages">
        <h2>Autres pages</h2>
        <p><a href="#Apropos">A propos</a></br>
        <a href="Aide.html">Aide</a></br>
        <a href="Forum.html">Forum</a></br>
        <a href="Copyright et mention légales">Copyright et mention légales</a></p></br>
        <hr class="hr" />
   </div>
    <div class="Réseaux sociaux">
           <h2>Rejoignez-nous sur</h2>
           <a href="https://www.facebook.com/Sportymates-1116430581702970/?ref=bookmarks"><img src="http://localhost/Sportymates1/images/logofacebook.jpg" alt="Logo Facebook" /></a>
           <a href="https://twitter.com/sportymates?lang=fr"><img src="http://localhost/Sportymates1/images/logotwitter.png" alt="Logo twitter" /></a>
           <a href="https://plus.google.com/"><img src="http://localhost/Sportymates1/images/logo%20googleplus.png" alt="Logo google plus" /></a>
    </div>
    <div class="finfooter">
    <p>© 2016  Sportymates</p>
   </div>
</div>
</body>
